id: 80000e9ad94e48268c0627c731d752fd
initial_creation_type: ocr
source_metadata:
  volumes:
    a1748fae50d44b81ba742487f1a62d2e:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: ''
      total_pages: 1349
      volume_number: 41
